name: readme_helper
description: Helpful code generator for README.md and other markdown files.
version: 0.0.1
homepage: https://github.com/felixblaschke/readme_helper

environment:
  sdk: ">=2.14.3 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
